<?php

namespace Workbench\App\Support;

use ZipArchive;

/**
 * Sample attachments generated at runtime, so the repository carries no
 * binary blobs. Used by the /send-attachments workbench route to exercise
 * every preview kind by hand.
 */
class Fixtures
{
    /**
     * A real PNG: a gradient with a border, so scaling is visible.
     */
    public static function png(int $width = 480, int $height = 280): string
    {
        $image = imagecreatetruecolor($width, $height);

        for ($x = 0; $x < $width; $x++) {
            $colour = imagecolorallocate(
                $image,
                (int) (245 - 120 * ($x / $width)),
                (int) (48 + 120 * ($x / $width)),
                (int) (3 + 90 * ($x / $width)),
            );
            imageline($image, $x, 0, $x, $height, $colour);
        }

        $white = imagecolorallocate($image, 255, 255, 255);
        imagerectangle($image, 8, 8, $width - 9, $height - 9, $white);
        imagestring($image, 5, 20, 20, 'laravel-mailroom', $white);

        ob_start();
        imagepng($image);
        imagedestroy($image);

        return (string) ob_get_clean();
    }

    /**
     * The same gradient re-encoded, so every raster kind the mailbox claims to
     * preview has something to show. gd reports support for all three.
     */
    public static function jpeg(): string
    {
        return self::reencode('jpeg');
    }

    public static function gif(): string
    {
        return self::reencode('gif');
    }

    public static function webp(): string
    {
        return self::reencode('webp');
    }

    protected static function reencode(string $format): string
    {
        $image = imagecreatefromstring(self::png(320, 180));

        ob_start();

        match ($format) {
            'jpeg' => imagejpeg($image, null, 82),
            'gif' => imagegif($image),
            'webp' => imagewebp($image, null, 82),
        };

        imagedestroy($image);

        return (string) ob_get_clean();
    }

    public static function svg(): string
    {
        return <<<'SVG'
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 200" width="320" height="200">
              <rect width="320" height="200" rx="14" fill="#1b1b18"/>
              <circle cx="160" cy="92" r="46" fill="#f53003"/>
              <text x="160" y="168" font-family="sans-serif" font-size="17" fill="#ededec" text-anchor="middle">
                vector attachment
              </text>
            </svg>
            SVG;
    }

    /**
     * A minimal but genuinely valid single-page PDF, written by hand so no
     * library is needed. Offsets in the xref table are computed rather than
     * hard-coded, otherwise viewers reject it.
     */
    public static function pdf(string $heading = 'laravel-mailroom'): string
    {
        $text = "BT /F1 24 Tf 72 700 Td ({$heading}) Tj ET\n"
            .'BT /F1 12 Tf 72 660 Td (Generated by the workbench for preview testing.) Tj ET';

        $objects = [
            "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
            "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
            "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
                ."/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj\n",
            "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
            '5 0 obj'."\n<< /Length ".strlen($text)." >>\nstream\n".$text."\nendstream\nendobj\n",
        ];

        $pdf = "%PDF-1.4\n";
        $offsets = [];

        foreach ($objects as $object) {
            $offsets[] = strlen($pdf);
            $pdf .= $object;
        }

        $xrefAt = strlen($pdf);

        $pdf .= 'xref'."\n0 ".(count($objects) + 1)."\n";
        $pdf .= "0000000000 65535 f \n";

        foreach ($offsets as $offset) {
            $pdf .= sprintf("%010d 00000 n \n", $offset);
        }

        $pdf .= 'trailer'."\n<< /Size ".(count($objects) + 1)." /Root 1 0 R >>\n";

        return $pdf.('startxref'."\n".$xrefAt."\n%%EOF\n");
    }

    /**
     * A short WAV tone, built from a raw PCM header plus samples.
     */
    public static function wav(int $milliseconds = 700, int $hz = 440): string
    {
        $rate = 8000;
        $samples = (int) ($rate * $milliseconds / 1000);
        $data = '';

        for ($i = 0; $i < $samples; $i++) {
            // Fade out so it does not click at the end.
            $envelope = 1 - ($i / $samples);
            $value = (int) (127 + 90 * $envelope * sin(2 * M_PI * $hz * $i / $rate));
            $data .= chr(max(0, min(255, $value)));
        }

        return 'RIFF'
            .pack('V', 36 + strlen($data))
            .'WAVEfmt '
            .pack('V', 16)
            .pack('v', 1)          // PCM
            .pack('v', 1)          // mono
            .pack('V', $rate)
            .pack('V', $rate)      // byte rate
            .pack('v', 1)          // block align
            .pack('v', 8)          // bits per sample
            .'data'
            .pack('V', strlen($data))
            .$data;
    }

    /**
     * A two-frame 160x90 H.264 clip.
     *
     * The only fixture here that is not generated in code. A PDF or a WAV can
     * be assembled from a header and a few objects, but a valid MP4 cannot --
     * it needs a real encoder. Shelling out to ffmpeg would mean the video
     * preview scenario silently disappears on any machine without it, which is
     * exactly the manual gap the seeder exists to close, so the bytes live
     * here instead.
     */
    public static function mp4(): string
    {
        return base64_decode(
            'AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAM2bW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAAA+gAAQAA'
            .'AQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
            .'AAAAAgAAAmB0cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAA+gAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAA'
            .'AAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAKAAAABaAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAPoAAAAAAABAAAAAAHY'
            .'bWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAABAAAAAQABVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRl'
            .'b0hhbmRsZXIAAAABg21pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAA'
            .'AQAAAUNzdGJsAAAAw3N0c2QAAAAAAAAAAQAAALNhdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAKAAWgBIAAAASAAAAAAA'
            .'AAABFUxhdmM2Mi4yOC4xMDIgbGlieDI2NAAAAAAAAAAAAAAAGP//AAAAOWF2Y0MBZAAM/+EAG2dkAAyscgRCjfkwEQAAAwAB'
            .'AAADAAQPFCmEYAEAB2joQ4GUsiz9+PgAAAAAEHBhc3AAAAABAAAAAQAAABRidHJ0AAAAAAAAFyAAAAAAAAAAGHN0dHMAAAAA'
            .'AAAAAQAAAAIAACAAAAAAFHN0c3MAAAAAAAAAAQAAAAEAAAAcc3RzYwAAAAAAAAABAAAAAQAAAAIAAAABAAAAHHN0c3oAAAAA'
            .'AAAAAAAAAAIAAALXAAAADQAAABRzdGNvAAAAAAAAAAEAAANmAAAAYnVkdGEAAABabWV0YQAAAAAAAAAhaGRscgAAAAAAAAAA'
            .'bWRpcmFwcGwAAAAAAAAAAAAAAAAtaWxzdAAAACWpdG9vAAAAHWRhdGEAAAABAAAAAExhdmY2Mi4xMi4xMDIAAAAIZnJlZQAA'
            .'AuxtZGF0AAACrwYF//+r3EXpvebZSLeWLNgg2SPu73gyNjQgLSBjb3JlIDE2NSByMzIyMiBiMzU2MDVhIC0gSC4yNjQvTVBF'
            .'Ry00IEFWQyBjb2RlYyAtIENvcHlsZWZ0IDIwMDMtMjAyNSAtIGh0dHA6Ly93d3cudmlkZW9sYW4ub3JnL3gyNjQuaHRtbCAt'
            .'IG9wdGlvbnM6IGNhYmFjPTEgcmVmPTE2IGRlYmxvY2s9MTowOjAgYW5hbHlzZT0weDM6MHgxMzMgbWU9dW1oIHN1Ym1lPTEw'
            .'IHBzeT0xIHBzeV9yZD0xLjAwOjAuMDAgbWl4ZWRfcmVmPTEgbWVfcmFuZ2U9MjQgY2hyb21hX21lPTEgdHJlbGxpcz0yIDh4'
            .'OGRjdD0xIGNxbT0wIGRlYWR6b25lPTIxLDExIGZhc3RfcHNraXA9MSBjaHJvbWFfcXBfb2Zmc2V0PS0yIHRocmVhZHM9MyBs'
            .'b29rYWhlYWRfdGhyZWFkcz0xIHNsaWNlZF90aHJlYWRzPTAgbnI9MCBkZWNpbWF0ZT0xIGludGVybGFjZWQ9MCBibHVyYXlf'
            .'Y29tcGF0PTAgY29uc3RyYWluZWRfaW50cmE9MCBiZnJhbWVzPTggYl9weXJhbWlkPTIgYl9hZGFwdD0yIGJfYmlhcz0wIGRp'
            .'cmVjdD0zIHdlaWdodGI9MSBvcGVuX2dvcD0wIHdlaWdodHA9MiBrZXlpbnQ9MjUwIGtleWludF9taW49MiBzY2VuZWN1dD00'
            .'MCBpbnRyYV9yZWZyZXNoPTAgcmNfbG9va2FoZWFkPTYwIHJjPWNyZiBtYnRyZWU9MSBjcmY9NTEuMCBxY29tcD0wLjYwIHFw'
            .'bWluPTAgcXBtYXg9NjkgcXBzdGVwPTQgaXBfcmF0aW89MS40MCBhcT0xOjEuMDAAgAAAACBliIEAAp8Wo/P/bWAwDH0eIepu'
            .'SlngAXt4BR4vdksdgQAAAAlBmggtiCX/Af4='
        );
    }

    public static function csv(int $rows = 40): string
    {
        $lines = ['order,customer,item,quantity,total'];

        for ($i = 1; $i <= $rows; $i++) {
            $lines[] = sprintf(
                'A-%04d,%s,"Widget, size %d",%d,%.2f',
                1000 + $i,
                ['Rachel Okonkwo', 'Sam Ihejirika', 'Dara Adeyemi', 'Kit Lindqvist'][$i % 4],
                $i % 5 + 1,
                $i % 3 + 1,
                19.99 * ($i % 3 + 1),
            );
        }

        return implode("\n", $lines)."\n";
    }

    public static function json(): string
    {
        return json_encode([
            'order' => 'A-1001',
            'customer' => ['name' => 'Rachel Okonkwo', 'email' => 'rachel@example.test'],
            'items' => [
                ['sku' => 'WIDGET-1', 'quantity' => 2, 'price' => 19.99],
                ['sku' => 'GIZMO-7', 'quantity' => 1, 'price' => 9.02],
            ],
            'total' => 49.00,
            'shipped_at' => '2026-07-30T09:14:00+00:00',
        ], JSON_UNESCAPED_SLASHES);
    }

    public static function tsv(): string
    {
        return implode("\n", [
            "order\tcustomer\ttotal",
            "A-1001\tRachel Okonkwo\t49.00",
            "A-1002\tSam Ihejirika\t19.99",
        ])."\n";
    }

    public static function markdown(): string
    {
        return <<<'MD'
            # Packing note

            Order **A-1001**, packed 30 July.

            - 2 x Widget, size 2
            - 1 x Gizmo

            > Someone must be home to sign for this.

            See `docs/shipping.md` for the full policy.
            MD;
    }

    public static function xml(): string
    {
        return <<<'XML'
            <?xml version="1.0" encoding="UTF-8"?>
            <order id="A-1001">
              <customer email="rachel@example.test">Rachel Okonkwo</customer>
              <items>
                <item sku="WIDGET-1" quantity="2">19.99</item>
                <item sku="GIZMO-7" quantity="1">9.02</item>
              </items>
              <total currency="GBP">49.00</total>
            </order>
            XML;
    }

    public static function yaml(): string
    {
        return <<<'YAML'
            order: A-1001
            customer:
              name: Rachel Okonkwo
              email: rachel@example.test
            items:
              - sku: WIDGET-1
                quantity: 2
              - sku: GIZMO-7
                quantity: 1
            total: 49.00
            YAML;
    }

    public static function sql(): string
    {
        return <<<'SQL'
            -- Snapshot of the order at dispatch.
            INSERT INTO orders (reference, customer_email, total_pence)
            VALUES ('A-1001', 'rachel@example.test', 4900);

            SELECT * FROM order_items WHERE order_reference = 'A-1001';
            SQL;
    }

    /**
     * Deliberately malformed, to exercise the "not valid JSON" preview note.
     */
    public static function brokenJson(): string
    {
        return '{"order": "A-1001", "total": , "items": [}';
    }

    /**
     * Over preview.max_inline_bytes, to exercise the "too large" state.
     */
    public static function oversizedText(int $bytes = 900 * 1024): string
    {
        $line = "This line exists only to push the file past the inline preview limit.\n";

        return str_repeat($line, (int) ceil($bytes / strlen($line)));
    }

    /**
     * Past preview.max_csv_rows, to exercise the truncation note.
     */
    public static function longCsv(int $rows = 500): string
    {
        return self::csv($rows);
    }

    public static function ics(): string
    {
        return implode("\r\n", [
            'BEGIN:VCALENDAR',
            'VERSION:2.0',
            'PRODID:-//laravel-mailroom//workbench//EN',
            'BEGIN:VEVENT',
            'UID:a-1001@example.test',
            'SUMMARY:Delivery window for order A-1001',
            'DTSTART;TZID=Europe/London:20260805T090000',
            'DTEND;TZID=Europe/London:20260805T130000',
            'LOCATION:14 Example Street\, London\, N1 9GU',
            'ORGANIZER;CN=Example App:mailto:app@example.test',
            'STATUS:CONFIRMED',
            'DESCRIPTION:Someone must be home to sign for this delivery.\nBring ID.',
            'END:VEVENT',
            'END:VCALENDAR',
        ])."\r\n";
    }

    public static function eml(): string
    {
        return implode("\r\n", [
            'From: Warehouse <warehouse@example.test>',
            'To: Support <support@example.test>',
            'Subject: Re: order A-1001 packed',
            'Date: Wed, 29 Jul 2026 16:02:11 +0000',
            'Message-ID: <packed-a-1001@example.test>',
            'Content-Type: text/plain; charset=utf-8',
            '',
            'Packed and on the van. Tracking follows separately.',
            '',
            '-- Warehouse',
        ])."\r\n";
    }

    /**
     * A structurally valid .docx, present purely to exercise the "no preview"
     * path. Office formats cannot be rendered without a service we are unable
     * to reach from a mailbox on localhost.
     */
    public static function docx(): ?string
    {
        if (! class_exists(ZipArchive::class)) {
            return null;
        }

        $path = tempnam(sys_get_temp_dir(), 'tmdocx');
        $zip = new ZipArchive;

        if ($zip->open($path, ZipArchive::OVERWRITE) !== true) {
            @unlink($path);

            return null;
        }

        $zip->addFromString('[Content_Types].xml',
            '<?xml version="1.0" encoding="UTF-8"?>'
            .'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
            .'<Default Extension="xml" ContentType="application/xml"/>'
            .'<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
            .'</Types>');

        $zip->addFromString('word/document.xml',
            '<?xml version="1.0" encoding="UTF-8"?>'
            .'<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
            .'<w:body><w:p><w:r><w:t>Invoice for order A-1001</w:t></w:r></w:p></w:body>'
            .'</w:document>');

        $zip->close();

        $contents = file_get_contents($path);
        @unlink($path);

        return $contents === false ? null : $contents;
    }
}
