<?php

namespace Workbench\App\Support;

use ZipArchive;

/**
 * Sample attachments generated at runtime, so the repository carries no
 * binary blobs. Used by the /send-attachments workbench route to exercise
 * every preview kind by hand.
 */
class Fixtures
{
    /**
     * A real PNG: a gradient with a border, so scaling is visible.
     */
    public static function png(int $width = 480, int $height = 280): string
    {
        $image = imagecreatetruecolor($width, $height);

        for ($x = 0; $x < $width; $x++) {
            $colour = imagecolorallocate(
                $image,
                (int) (245 - 120 * ($x / $width)),
                (int) (48 + 120 * ($x / $width)),
                (int) (3 + 90 * ($x / $width)),
            );
            imageline($image, $x, 0, $x, $height, $colour);
        }

        $white = imagecolorallocate($image, 255, 255, 255);
        imagerectangle($image, 8, 8, $width - 9, $height - 9, $white);
        imagestring($image, 5, 20, 20, 'laravel-test-mail', $white);

        ob_start();
        imagepng($image);
        imagedestroy($image);

        return (string) ob_get_clean();
    }

    public static function svg(): string
    {
        return <<<'SVG'
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 200" width="320" height="200">
              <rect width="320" height="200" rx="14" fill="#1b1b18"/>
              <circle cx="160" cy="92" r="46" fill="#f53003"/>
              <text x="160" y="168" font-family="sans-serif" font-size="17" fill="#ededec" text-anchor="middle">
                vector attachment
              </text>
            </svg>
            SVG;
    }

    /**
     * A minimal but genuinely valid single-page PDF, written by hand so no
     * library is needed. Offsets in the xref table are computed rather than
     * hard-coded, otherwise viewers reject it.
     */
    public static function pdf(string $heading = 'laravel-test-mail'): string
    {
        $text = "BT /F1 24 Tf 72 700 Td ({$heading}) Tj ET\n"
            .'BT /F1 12 Tf 72 660 Td (Generated by the workbench for preview testing.) Tj ET';

        $objects = [
            "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
            "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
            "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
                ."/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj\n",
            "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
            '5 0 obj'."\n<< /Length ".strlen($text)." >>\nstream\n".$text."\nendstream\nendobj\n",
        ];

        $pdf = "%PDF-1.4\n";
        $offsets = [];

        foreach ($objects as $object) {
            $offsets[] = strlen($pdf);
            $pdf .= $object;
        }

        $xrefAt = strlen($pdf);

        $pdf .= 'xref'."\n0 ".(count($objects) + 1)."\n";
        $pdf .= "0000000000 65535 f \n";

        foreach ($offsets as $offset) {
            $pdf .= sprintf("%010d 00000 n \n", $offset);
        }

        $pdf .= 'trailer'."\n<< /Size ".(count($objects) + 1)." /Root 1 0 R >>\n";

        return $pdf.('startxref'."\n".$xrefAt."\n%%EOF\n");
    }

    /**
     * A short WAV tone, built from a raw PCM header plus samples.
     */
    public static function wav(int $milliseconds = 700, int $hz = 440): string
    {
        $rate = 8000;
        $samples = (int) ($rate * $milliseconds / 1000);
        $data = '';

        for ($i = 0; $i < $samples; $i++) {
            // Fade out so it does not click at the end.
            $envelope = 1 - ($i / $samples);
            $value = (int) (127 + 90 * $envelope * sin(2 * M_PI * $hz * $i / $rate));
            $data .= chr(max(0, min(255, $value)));
        }

        return 'RIFF'
            .pack('V', 36 + strlen($data))
            .'WAVEfmt '
            .pack('V', 16)
            .pack('v', 1)          // PCM
            .pack('v', 1)          // mono
            .pack('V', $rate)
            .pack('V', $rate)      // byte rate
            .pack('v', 1)          // block align
            .pack('v', 8)          // bits per sample
            .'data'
            .pack('V', strlen($data))
            .$data;
    }

    public static function csv(int $rows = 40): string
    {
        $lines = ['order,customer,item,quantity,total'];

        for ($i = 1; $i <= $rows; $i++) {
            $lines[] = sprintf(
                'A-%04d,%s,"Widget, size %d",%d,%.2f',
                1000 + $i,
                ['Rachel Okonkwo', 'Sam Ihejirika', 'Dara Adeyemi', 'Kit Lindqvist'][$i % 4],
                $i % 5 + 1,
                $i % 3 + 1,
                19.99 * ($i % 3 + 1),
            );
        }

        return implode("\n", $lines)."\n";
    }

    public static function json(): string
    {
        return json_encode([
            'order' => 'A-1001',
            'customer' => ['name' => 'Rachel Okonkwo', 'email' => 'rachel@example.test'],
            'items' => [
                ['sku' => 'WIDGET-1', 'quantity' => 2, 'price' => 19.99],
                ['sku' => 'GIZMO-7', 'quantity' => 1, 'price' => 9.02],
            ],
            'total' => 49.00,
            'shipped_at' => '2026-07-30T09:14:00+00:00',
        ], JSON_UNESCAPED_SLASHES);
    }

    public static function ics(): string
    {
        return implode("\r\n", [
            'BEGIN:VCALENDAR',
            'VERSION:2.0',
            'PRODID:-//laravel-test-mail//workbench//EN',
            'BEGIN:VEVENT',
            'UID:a-1001@example.test',
            'SUMMARY:Delivery window for order A-1001',
            'DTSTART;TZID=Europe/London:20260805T090000',
            'DTEND;TZID=Europe/London:20260805T130000',
            'LOCATION:14 Example Street\, London\, N1 9GU',
            'ORGANIZER;CN=Example App:mailto:app@example.test',
            'STATUS:CONFIRMED',
            'DESCRIPTION:Someone must be home to sign for this delivery.\nBring ID.',
            'END:VEVENT',
            'END:VCALENDAR',
        ])."\r\n";
    }

    public static function eml(): string
    {
        return implode("\r\n", [
            'From: Warehouse <warehouse@example.test>',
            'To: Support <support@example.test>',
            'Subject: Re: order A-1001 packed',
            'Date: Wed, 29 Jul 2026 16:02:11 +0000',
            'Message-ID: <packed-a-1001@example.test>',
            'Content-Type: text/plain; charset=utf-8',
            '',
            'Packed and on the van. Tracking follows separately.',
            '',
            '-- Warehouse',
        ])."\r\n";
    }

    /**
     * A structurally valid .docx, present purely to exercise the "no preview"
     * path. Office formats cannot be rendered without a service we are unable
     * to reach from a mailbox on localhost.
     */
    public static function docx(): ?string
    {
        if (! class_exists(ZipArchive::class)) {
            return null;
        }

        $path = tempnam(sys_get_temp_dir(), 'tmdocx');
        $zip = new ZipArchive;

        if ($zip->open($path, ZipArchive::OVERWRITE) !== true) {
            @unlink($path);

            return null;
        }

        $zip->addFromString('[Content_Types].xml',
            '<?xml version="1.0" encoding="UTF-8"?>'
            .'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
            .'<Default Extension="xml" ContentType="application/xml"/>'
            .'<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
            .'</Types>');

        $zip->addFromString('word/document.xml',
            '<?xml version="1.0" encoding="UTF-8"?>'
            .'<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
            .'<w:body><w:p><w:r><w:t>Invoice for order A-1001</w:t></w:r></w:p></w:body>'
            .'</w:document>');

        $zip->close();

        $contents = file_get_contents($path);
        @unlink($path);

        return $contents === false ? null : $contents;
    }
}
